"""index on fetched_at

Revision ID: 5eac7e17e3cc
Revises: 28e45126c68f
Create Date: 2026-01-05 22:48:57.355142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eac7e17e3cc'
down_revision: Union[str, Sequence[str], None] = '28e45126c68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_weather_city_fetched_at', 'weather', ['city', sa.literal_column('fetched_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_city_fetched_at', table_name='weather')
    # ### end Alembic commands ###
